export const LOADING_ON = "LOADING_ON";
export const LOADING_OFF = "LOADING_OFF";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const AUTH_UPDATE_START = "AUTH_UPDATE_START";
export const AUTH_UPDATE_SUCCESS = "AUTH_UPDATE_SUCCESS";
export const AUTH_UPDATE_FAIL = "AUTH_UPDATE_END";
export const AUTH_UPDATE_FINISH = "AUTH_UPDATE_FINISH";

export const ACCOUNT_LOADING = "ACCOUNT_LOADING";
export const ACCOUNT_FETCH_SUCCESS = "ACCOUNT_FETCH_SUCCESS";
export const ACCOUNT_FETCH_FAIL = "ACCOUNT_FETCH_FAIL";

export const NOTIFICATION_LOADING = "NOTIFICATION_LOADING";
export const NOTIFICATION_FETCH_ALL_SUCCESS = "NOTIFICATION_FETCH_ALL_SUCCESS";
export const NOTIFICATION_FETCH_ALL_FAIL = "NOTIFICATION_FETCH_ALL_FAIL";

export const ORDER_FETCH_ALL_ACTIVE_START = "ORDER_FETCH_ALL_START";
export const ORDER_FETCH_ALL_ACTIVE_SUCCESS = "ORDER_FETCH_ALL_SUCCESS";
export const ORDER_FETCH_ALL_ACTIVE_FAIL = "ORDER_FETCH_ALL_FAIL";
export const ORDER_FETCH_ALL_ACTIVE_FINISH = "ORDER_FETCH_ALL_ACTIVE_FINISH";
export const ORDER_FETCH_ALL_HISTORY_START = "ORDER_FETCH_ALL_HISTORY_START";
export const ORDER_FETCH_ALL_HISTORY_SUCCESS = "ORDER_FETCH_ALL_HISTORY_SUCCESS";
export const ORDER_FETCH_ALL_HISTORY_FAIL = "ORDER_FETCH_ALL_HISTORY_FAIL";
export const ORDER_FETCH_ALL_HISTORY_FINISH = "ORDER_FETCH_ALL_HISTORY_FINISH";
export const ORDER_CREATE_START = "ORDER_CREATE_START";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_FINISH = "ORDER_CREATE_FINISH";
export const ORDER_CLOSE_START = "ORDER_CLOSE_START";
export const ORDER_CLOSE_SUCCESS = "ORDER_CLOSE_SUCCESS";
export const ORDER_CLOSE_FAIL = "ORDER_CLOSE_FAIL";
export const ORDER_CLOSE_FINISH = "ORDER_CLOSE_FINISH";

export const PRICES_FETCH_START = "PRICES_FETCH_START";
export const PRICES_FETCH_SUCCESS = "PRICES_FETCH_SUCCESS";
export const PRICES_FETCH_FAIL = "PRICES_FETCH_FAIL";

export const ALARM_FETCH_START = "ALARM_FETCH_START";
export const ALARM_FETCH_SUCCESS = "ALARM_FETCH_SUCCESS";
export const ALARM_FETCH_FAIL = "ALARM_FETCH_FAIL";
export const ALARM_FETCH_FINISH = "ALARM_FETCH_FINISH";
export const ALARM_CREATE_START = "ALARM_CREATE_START";
export const ALARM_CREATE_SUCCESS = "ALARM_CREATE_SUCCESS";
export const ALARM_CREATE_FAIL = "ALARM_CREATE_FAIL";
export const ALARM_CREATE_FINISH = "ALARM_CREATE_FINISH";
export const ALARM_DELETE_START = "ALARM_DELETE_START";
export const ALARM_DELETE_SUCCESS = "ALARM_DELETE_SUCCESS";
export const ALARM_DELETE_FAIL = "ALARM_DELETE_FAIL";
export const ALARM_DELETE_FINISH = "ALARM_DELETE_FINISH";
